name: Build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure CMake
        run: cmake -B_build

      - name: Build project
        run: |
          cmake --build _build --config Release


  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        mkdir third-party
        mkdir artifacts
        git submodule add https://github.com/google/googletest third-party/gtest
        cd third-party/gtest && git checkout release-1.11.0 && cd ../..
        cmake -H. -B_build -DBUILD_TESTS=ON
        cmake --build _build
    - name: Tests
      run:  _build/check
